apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage2-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage2
  template:
    metadata:
      labels:
        app: webpage2
    spec:
      containers:
      - name: webpage2
        image: <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/webpage2:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webpage2-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: webpage2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
