apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage1-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage1
  template:
    metadata:
      labels:
        app: webpage1
    spec:
      containers:
      - name: webpage1
        image: <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/webpage1:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webpage1-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: webpage1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
